name: cleanup-merged-branches.yaml
on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-merged-branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Delete merged branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "Deleting branch: $BRANCH_NAME"
          gh api repos/{owner}/{repo}/branches/$BRANCH_NAME/rename \
              -f "new_name=merged/$BRANCH_NAME"
          
          git push origin --delete merged/$BRANCH_NAME